services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: gbs
      MONGO_INITDB_ROOT_PASSWORD: geheim

  webapi:
    build: ./WebApi
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    environment:
      - ASPNETCORE_URLS=http://+:5001
      - DatabaseSettings__ConnectionString=mongodb://gbs:geheim@mongodb:27017

#  frontend:
#    build: ./mini-frontend-m347
#    container_name: frontend
#    ports:
#      - "3000:80"
# 
#  nginx:
#    image: nginx:alpine
#    container_name: nginx
#    ports:
#      - "8080:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#    depends_on:
#      - webapi
#      - frontend

volumes:
    mongo-data: